### ISSUE TITLE
Heavy operations on strings  because of _printDebug

### ISSUE THREAD

**Issue by ASGAlex** [lamnhan066/isolate_manager#17]
Code like 
```
_printDebug('Message send to isolate: $message');
```
consumes a lot of resources if your message is relatively big. For example, I pack my classes to binary view using flat buffers, but this debug string ruins all my efforts to send data swiftly. 
![image](https://github.com/lamnhan066/isolate_manager/assets/1258285/cdd12b0f-b655-4c26-a55f-5fa0f8c7814c)

Changing _debugMode will not solve the problem because debug string is created before function call.

**Comment by lamnhan066** [comment]
Thank you for pointing this issue out, I'll release a fix soon.
