### ISSUE TITLE
generate gives issue: Error: Dart library 'dart:ui' is not available on this platform.

### ISSUE THREAD

**Issue by ujwalbasnet1** [lamnhan066/isolate_manager#20]
[output.log](https://github.com/user-attachments/files/16115128/output.log)

**Comment by lamnhan066** [comment]
The Dart `wasm` (and `js`) compiler does not support the `dart:ui` package, which is used by the `material.dart` and other UI components. To ensure your functions work as expected, store them in a separate file and make sure they do not depend on those UI components.

**Comment by ujwalbasnet1** [comment]
i am working on pdf generation on bg that depends on UI..

isolate works good for macos (maybe it will work on other non-web platforms too - not tested yet)

but web generation failed..

any idea on how can I separate those?

**Comment by lamnhan066** [comment]
If the dependent is necessary, you can leave the `workerName` parameter empty so that the `Future` will be used instead of the `Worker`. If the performance is really poor, you need to find an alternative method to make it independent of the UI components.

**Comment by ujwalbasnet1** [comment]
Thanks
