### ISSUE TITLE
Generator stuck on "Total files to generate"

### ISSUE THREAD

**Issue by chaudharydeepanshu** [lamnhan066/isolate_manager#21]
The generator didn't work when I tried.

```
dart run isolate_manager:generate                           
Building package executable... (7.7s)
Built isolate_manager:generate.
>> Generating the single Workers...
Parsing the `IsolateManagerWorker` inside directory: lib...
Total files to generate: 1
...
```

I left it for 10 minutes but it didn't finish.  Let me know if you need anything further to analyse it.

**Flutter doctor res:**

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.4037], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.6)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.92.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

**Comment by lamnhan066** [comment]
Hi @chaudharydeepanshu, could you provide minimal code to reproduce this issue? It still works well when I try generating in the example.

**Comment by chaudharydeepanshu** [comment]
Sorry, I found it was my mistake. The function had many dependencies on Flutter, so after removing those dependencies, it’s now generating.

One question: For web, we only need to run the generator? Also, when I tried running app without the worker.js, I got no result on web. Is this how it is intended to work or should it have fallback to run on the main thread?

**Comment by lamnhan066** [comment]
> One question: For web, we only need to run the generator?

When you want to use the Worker on the web, you have to specify the `useWorker` in the `IsolateManager.createShared` and the `workerName` in the `IsolateManager.create` or `IsolateManager.createCustom`. 

> Also, when I tried running app without the worker.js, I got no result on web. Is this how it is intended to work or should it have fallback to run on the main thread?

I used to think about this issue but haven't found an effective way to check whether the `worker.js` file exists to fallback to run without the Worker. So if you want to use the Worker, you have to make sure that the `worker.js` exists. Otherwise, you can ignore the `useWorker` and `workerName` parameters.

**Comment by chaudharydeepanshu** [comment]
Okay, if I ignore the `workerName`, the function will run on the `main` on the web?

Right now, my functions rely on Flutter dependencies, so migrating them all would be pain to generate the worker.js. So, is there a way to avoid running on the main thread without having to generate the worker.js file?

**Comment by lamnhan066** [comment]
> Okay, if I ignore the workerName, the function will run on the main on the web?

Yes, the function will run on the `main` app when you ignore the `workerName` parameter, so the app may be frozen when calculating an expensive function.

> So, is there a way to avoid running on the main thread without having to generate the worker.js file?

There is no way to do that right now. There is a small trick to avoid UI frozen when you're using a loop is adding `await Future.delayed(Duration.zero);` like this:

```dart
Future<int> fibonacciFuture(int n) async {
  if (n == 0) return 0;
  if (n <= 2) return 1;

  double n1 = 0, n2 = 1, n3 = 1;

  for (int i = 2; i <= n; i++) {
    n3 = n1 + n2;
    n1 = n2;
    n2 = n3;

    // Magic code: This is only for non-blocking UI on the Web platform
    await Future.delayed(Duration.zero);
  }

  return n3.round();
}
```

**Comment by chaudharydeepanshu** [comment]
> There is a small trick to avoid UI frozen when you're using a loop is adding await Future.delayed(Duration.zero);

Got it, thanks. I do have a loop, but the computation is complex, and the loop has large number of iterations. I’ll still add this to see how much it helps in that case. But I guess I will refactor the code to create workers for those functions.

Also, I’ll try to create reproducible code for generator stuck indefinitely, as it shouldn’t get stuck and should throw error in my opinion. Once I have a sample code maybe we can reopen the issue or I will create a new one.

Thanks for the prompt response and resolution.

**Comment by lamnhan066** [comment]
Feel free to reopen this issue or create a new one when you have a reproducible code. Thank you.
