### ISSUE TITLE
Performance Issue When Picking Large Excel Files with isolate_manager

### ISSUE THREAD

**Issue by MushtaqAhmadMir** [lamnhan066/isolate_manager#23]
I'm encountering performance issues when picking large Excel files in my Flutter web app. The UI becomes unresponsive while processing these files, likely because of heavy file operations being done on the main thread. I am currently using isolate_manager to offload some of the work to a background isolate, but the issue persists for large files.

**Steps to Reproduce:**
Use the following code to pick and process an Excel file.
Try uploading a large Excel file (e.g., > 10MB).
The UI freezes until the file is completely processed.

**Expected Behavior:**
The file processing should happen asynchronously in the background, without freezing the UI.
A loader or some form of UI feedback should be visible while the file is being processed.

**Actual Behavior:**
The UI freezes until the entire Excel file is processed, especially for large files.

```
import 'package:file_picker/file_picker.dart';
import 'package:excel/excel.dart';
import 'package:isolate_manager/isolate_manager.dart';
import 'dart:async';

class UploadDialogBox extends StatefulWidget {
  // Other implementation details here...
}

class _UploadDialogBoxState extends State<UploadDialogBox> {
  List<ExcelSheetModel> sheetInfoList = [];
  late final IsolateManager isolateManager;

  @override
  void initState() {
    super.initState();
    isolateManager = IsolateManager.createCustom(
      concurrent: 2,
      isolateFunction,
      isDebug: true,
    );
    isolateManager.start();
  }

  FutureOr<void> isolateFunction(dynamic val) async {
    await excelPicker(); // Heavy Excel processing logic here
  }

  FutureOr<dynamic> excelPicker() async {
    FilePickerResult? pickedFile = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['xlsx'],
      allowMultiple: false,
    );

    if (pickedFile != null) {
      var bytes = pickedFile.files.single.bytes;
      var excel = Excel.decodeBytes(bytes!.toList());

      excel.sheets.forEach((name, sheet) {
        // Adding sheet data to the model
      });

      setState(() {
        // Update the UI once processing is complete
      });
    }
  }

  @override
  void dispose() {
    isolateManager.stop();
    super.dispose();
  }
}
```
**Proposed Solution:**
Offload the entire file processing to an isolate using isolate_manager or improve the performance of file operations for large Excel files.
Provide an example or documentation on how to handle large files more efficiently using isolate_manager.

**Comment by lamnhan066** [comment]
Hi @MushtaqAhmadMir 

The UI was frozen because it wasn't using a real Isolate on the Web. You need to create a JS Worker or use a built-in generator (read more in README) to generate it to completely offroad the entire file processing.
