### ISSUE TITLE
Unable to Pass Map as Input/Output in isolate-manager Causing UI Freeze on jsonEncode/jsonDecode

### ISSUE THREAD

**Issue by abbashosseinii** [lamnhan066/isolate_manager#31]
Hello,

I encountered an issue while using the isolate-manager package. It seems that I’m unable to pass a Map as an input or output when using isolate-manager, which leads to problems when handling large data transfers.

As a workaround, I was able to send and receive a Map using a worker without any issues. However, when attempting the same process using isolate-manager, the error occurs, and the UI freezes during jsonEncode and jsonDecode.

Is there any way to resolve this issue or support passing a Map?

Thank you for your assistance!

Steps to Reproduce:

	1.	Try passing a Map as an input or output in isolate-manager.
	2.	Experience the No such method error.

Expected Behavior:

Be able to pass a Map without encountering an error.

Environment:

	•	Flutter version: (3.24.3)
	•	isolate-manager version: (^5.3.0)
	•	Device: (chrome)

**Comment by lamnhan066** [comment]
Hi @abbashosseinii 

Can you let me know the way that you send and receive a Map via Worker? I think we have no similar Dart Map in JS so we cannot send a Map directly to the JS. The only way I can do is by using `jsonEncode` and `jsonDecode`.

**Comment by abbashosseinii** [comment]
Hello dear @lamnhan066 
This is possible. We just need our models to work with `Map<dynamic, dynamic>` in the `toJson` and `fromJson` methods. I wrote a simple project where I implemented this using a basic `worker.js`. I’ll attach the project link below. Thank you for your quick response.
[Sample project](https://github.com/abbashosseinii/Worker-With-Supporting-Map)

**Comment by lamnhan066** [comment]
Hi @abbashosseinii 

If you are using the `toJson` and `fromJson` the the package will work flawlessly when you're using String like this (I copied this from the [document](https://pub.dev/packages/isolate_manager#additional-information)) :

```dart
main() async {
  final isolate = IsolateManager.create(
    aStringIntMap,
    workerName: 'aStringIntMap',
    isDebug: true,
  );
  await isolate.start();

  final map = {'a': 1, 'b': 2, 'c': 3};
  final result = await isolate.compute(jsonEncode(map));
  expect(jsonDecode(result), map);
}

@isolateManagerWorker
String aStringIntMap(String params) {
  return params;
}
```

**Comment by abbashosseinii** [comment]
Dear @lamnhan066

I opened this issue for three reasons:

#### 1- The reason for choosing the package
The solution you provided for encoding and decoding is not compatible with the web platform, and the main reason I chose this package over conventional methods is to leverage multi-threading in the web environment.

#### 2- Compatibility with very large data
In cases where large amounts of data need to be transferred, like in the project I’m currently working on, this encoding and decoding process becomes a very time-consuming operation.

#### 3- Work smarter, not harder
We can only solve this issue if we remove the current limitations on input and output and handle it through Map, as I explained earlier. This way, we can significantly reduce the computational load and noticeably shorten task completion times.

**Comment by lamnhan066** [comment]
Hi @abbashosseinii 

I misunderstood your last opinion because at first, I thought your `toJson` returns a `String` instead of a `Map`. I just realized that when I looked into the `worker.js`. I think the issue was caused when compiling from Dart to JS (your script was written in JS native).

I think I will try to write a simple script in Dart using a `Map`, compile it to JS and let’s see if I can find any way to make it work.

Thank you for your information.

**Comment by abbashosseinii** [comment]
@lamnhan066
Thank you so much! Wish you success!

**Comment by lamnhan066** [comment]
@abbashosseinii 

After doing a small test, I realized that the issue was caused by the `web` package. With the same kind of the `worker.dart`, I can send the Map<dynamic, dynamic> between the main app and the `Worker` when using the `Worker` from the `html` package, but I cannot do it when using the `Worker` from the `web` and `js_interop`.

This is the demo for the `web` package:

`worker.dart`
```dart
import 'dart:js_interop';

import 'package:web/web.dart';

@JS('self')
external DedicatedWorkerGlobalScope get self;

void main() {
  self.onmessage = (MessageEvent event) {
    self.postMessage([event.data] as dynamic);
  }.toJS;
}
```

`runWorker`
```dart
  Future<Map<dynamic, dynamic>> runWorker(Map<dynamic, dynamic> inputData) async {
    // Create a new worker
    final worker = web.Worker('out.js'.toJS);

    // Prepare a completer to handle async communication
    final completer = Completer<Map<dynamic, dynamic>>();

    // Listen for messages from the worker
    worker.onmessage = ((web.MessageEvent event) {
      final updatedData = event.data;
      completer.complete(updatedData as Map<dynamic, dynamic>);
      worker.terminate(); // Terminate worker when done
    }).toJS;

    // Send the input data to the worker
    worker.postMessage(inputData as dynamic);

    // Wait for the result
    return completer.future;
  }
```

And for the `html` package:

`worker.dart`
```dart
import 'dart:js_interop';

import 'package:universal_html/html.dart';

@JS('self')
external DedicatedWorkerGlobalScope get self;

void main() {
  self.onMessage.listen((event) {
    self.postMessage(event.data);
  });
}
```

`runWorker` is the same as your demo.

You can run `dart compile js worker.dart` for each one and copy the `out.js` to the web folder to check the result.

**Comment by lamnhan066** [comment]
By using the code from [here](https://github.com/firebase/flutterfire/blob/main/packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart), I can pass a Map between the main app and the Worker flawlessly. I'll release a new version as soon as all tests pass.
