### ISSUE TITLE
Uncaught Error: UnimplementedError

### ISSUE THREAD

**Issue by WieFel** [lamnhan066/isolate_manager#35]
I have the following code, which I run on an isolate. It has two functions `exportAsCsv` and `exportAsExcel` (in a separate dart file), which depend on an external lib respectively.
```dart
import 'package:csv/csv.dart';
import 'package:excel/excel.dart';
import 'package:isolate_manager/isolate_manager.dart';

@pragma('vm:entry-point')
@isolateManagerWorker
Future<List<int>> exportAsCsv(List<List<dynamic>> data) async {
  final csv = ListToCsvConverter().convert(data);
  return csv.codeUnits;
}

@pragma('vm:entry-point')
@isolateManagerWorker
Future<List<int>> exportAsExcel(({String fileName, List<List<dynamic>> data}) message) async {
  final excel = Excel.createExcel();
  final sheet = excel['Sheet1'];

  for (final row in message.data) {
    sheet.appendRow(List.of(row.map((cellValue) => TextCellValue(cellValue.toString()))));
  }
  List<int>? bytes = excel.save(fileName: message.fileName);

  if (bytes == null) {
    throw Exception('Failed to save Excel file');
  }

  return bytes;
}
```
I instantiate the isolate managers like this in my Bloc:
```dart
final csvIsolateManager = IsolateManager.create(
  exportAsCsv,
  workerName: 'exportAsCsv',
);
final excelIsolateManager = IsolateManager.create(
  exportAsExcel,
  workerName: 'exportAsExcel',
);
```

On Android/iOS, the code runs fine.
When I run it on web, and trigger e.g. the `exportToCsv()` function, I get the following error in my browser console:
```javascript
Uncaught Error: UnimplementedError
    at Object.b (exportAsCsv.js:249:18)
    at Object.bT (exportAsCsv.js:258:15)
    at cm.gb_ (exportAsCsv.js:3965:16)
    at exportAsCsv.js:2029:3
    at fw.a (exportAsCsv.js:1329:64)
    at fw.$2 (exportAsCsv.js:2462:14)
    at Object.h5 (exportAsCsv.js:1315:11)
    at Object.hg (exportAsCsv.js:2032:10)
    at kQ (exportAsCsv.js:2055:8)
    at exportAsCsv.js:4430:66
```

I suppose that is due to `isolate_manager` not supporting ANY external packages.. Is that true?
Is there any way I can get it to work on web?

**Comment by lamnhan066** [comment]
Hi @WieFel 

Have you run the `dart run isolate_manager:generate` and is it completed?

If the `csv` and `excel` support the Dart native then the isolate should work after the generation is complete.

**Comment by WieFel** [comment]
Thanks for the quick answer.

Yes, I ran `dart run isolate_manager:generate`, and it generated two files `exportAsCsv.js` and `exportAsExcel.js`.

And yes, the packages actually both support web:
https://pub.dev/packages/csv
https://pub.dev/packages/excel

When I run them just with the normal dart `compute()` function, they run fine on the web, but they block the UI of course.

I just don't really understand what the `UnimplementedError` tells me in this case, as the js code is obfuscated...

**Comment by lamnhan066** [comment]
I think the issue is caused by `excel.save`, it executes the download dialog which isn’t supported on the Worker. Is there any other method that does the same without triggering the native UI part like dialog?

**Comment by WieFel** [comment]
True, it is triggering the download directly. But no download dialog.

However, `exportAsCsv` doesn't do that, and still fails. I also triggered `exportAsCsv` in the example that failed...

**Comment by lamnhan066** [comment]
You can try using the List<dynamic> instead of a specific Type like this:

```dart
@isolateManagerWorker
Future<List> exportAsCsv(List data) async {
  final csv = ListToCsvConverter().convert(data);
  return csv.codeUnits;
}
```

**Comment by lamnhan066** [comment]
You can add a `--obfuscate 0` to avoid the obfuscation, so you can easier to debug the code. I haven’t a computer right now so I can’t test it myself.

**Comment by WieFel** [comment]
Ok, like that the error message is a little clearer:
```js
Uncaught Error: UnimplementedError
    at Object.wrapException (exportAsCsv.js:862:43)
    at Object.throwExpression (exportAsCsv.js:881:15)
    at IsolateContactorControllerImplWorker.get$onIsolateMessage (exportAsCsv.js:13877:16)
    at IsolateManagerControllerImpl.get$onIsolateMessage (exportAsCsv.js:14000:34)
    at IsolateManagerController.get$onIsolateMessage (exportAsCsv.js:13986:29)
    at exportAsCsv.js:7077:26
    at _wrapJsFunctionForAsync_closure.$protected (exportAsCsv.js:3805:15)
    at _wrapJsFunctionForAsync_closure.call$2 (exportAsCsv.js:8417:12)
    at Object._asyncStartSync (exportAsCsv.js:3770:20)
    at Object.isolateWorkerImpl (exportAsCsv.js:7083:16)
```

**Comment by lamnhan066** [comment]
The issue comes from somewhere here:

https://github.com/lamnhan066/isolate_manager/blob/main/lib/src/isolate_worker/isolate_worker_web.dart#L24-L36

Because no test covers the 2D input so it may be the root one that causes the issue.

**Comment by lamnhan066** [comment]
Hi @WieFel 

The code will work when I add `.toList()` like this

```dart
@pragma('vm:entry-point')
@isolateManagerWorker
Future<List> exportAsCsv(List data) async {
  final csv = data.map((d) => d.join(',')).join('\n');
  return csv.codeUnits.toList();
}
```

When I debug by printing the `csv.codeUnits.runtimeType` , the `.codeUnit` returns a `CodeUnits` instead of a List, so the IsolateManger cannot cast it to the List as expected Type.

**Comment by WieFel** [comment]
Thanks for the help.

> ```dart
> @pragma('vm:entry-point')
> @isolateManagerWorker
> Future<List> exportAsCsv(List data) async {
>   final csv = data.map((d) => d.join(',')).join('\n');
>   return csv.codeUnits.toList();
> }
> ```

However, when I use the exact same code here, and generate the js files again, I still get the following error:
```js
exportAsCsv.js:862 Uncaught Error: UnimplementedError
    at Object.wrapException (exportAsCsv.js:862:43)
    at Object.throwExpression (exportAsCsv.js:881:15)
    at IsolateContactorControllerImplWorker.get$onIsolateMessage (exportAsCsv.js:13877:16)
    at IsolateManagerControllerImpl.get$onIsolateMessage (exportAsCsv.js:14000:34)
    at IsolateManagerController.get$onIsolateMessage (exportAsCsv.js:13986:29)
    at exportAsCsv.js:7077:26
    at _wrapJsFunctionForAsync_closure.$protected (exportAsCsv.js:3805:15)
    at _wrapJsFunctionForAsync_closure.call$2 (exportAsCsv.js:8417:12)
    at Object._asyncStartSync (exportAsCsv.js:3770:20)
    at Object.isolateWorkerImpl (exportAsCsv.js:7083:16)
```

Could it be related with my Dart/Flutter version?
<details>
  <summary>Here is my Flutter doctor output</summary>
  
```
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.5 23F79 darwin-arm64, locale en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.94.2)
[✓] Connected device (3 available)
[✓] Network resources
```
</details>

**Comment by lamnhan066** [comment]
I'm using the same Flutter version as yours. Here is my test code and the result:

<img width="934" alt="image" src="https://github.com/user-attachments/assets/fdd4ce0d-5182-4b10-951a-0a6b99d58d15">

<details>
<summary>Code</summary>

    import 'package:isolate_manager/isolate_manager.dart';
    import 'package:test/test.dart';
    
    // dart test --platform=chrome test/csv.dart
    
    void main() async {
      test('', () async {
        final im = IsolateManager.create(
          exportAsCsv,
          workerName: 'exportAsCsv',
          isDebug: true,
        );
    
        final map = [
          ['a', 'b', 'c'],
          ['d', 'e', 'f'],
        ];
    
        print(await im.compute(map));
      });
    }
    
    @pragma('vm:entry-point')
    @isolateManagerWorker
    Future<List> exportAsCsv(List data) async {
      final csv = data.map((d) => d.join(',')).join('\n');
      return csv.codeUnits.toList();
    }

</details>

**Comment by WieFel** [comment]
Thank you.
Now I got it to work for the csv export function like so:
```dart
@pragma('vm:entry-point')
@isolateManagerWorker
Future<List> exportAsCsv(List<List> data) async {
  final csv = ListToCsvConverter().convert(data);
  return csv.codeUnits;
}
```

When running the function with the isolate manager, I need to cast the return type accordingly now:
```dart
final csv = List<int>.from(await csvIsolateManager.compute(data));
```

**However**, when I now use the same approach for the `exportAsExcel` function, it breaks both, the csv export and the excel export on web again...

**Comment by lamnhan066** [comment]
Have you tried using `csv.codeUnits.toList()` instead of only `csv.codeUnits`? The `to list()` is very important when you want to compile it into a Worker.

**Comment by lamnhan066** [comment]
Feel free to re-open this issue if you still have the same issue.
