### ISSUE TITLE
IsolateManager Does Not Properly Handle Exceptions: Subsequent Tasks Are Not Processed

### ISSUE THREAD

**Issue by stephane-archer** [lamnhan066/isolate_manager#41]
``` Dart
import 'dart:io';
import 'package:isolate_manager/isolate_manager.dart';

Future<void> _updateJpegToJxlStat(
  Future<String> future,
) async {
  try {
    String convertionStats = await future;
    print("success $convertionStats");
  } catch (e) {
    print("fail $e");
  }
}

Future<String> convert(String message) {
  throw "convert error"; // simulate an error
}

Future<void> processJpegFiles(
  Iterable<File> jpegFiles,
) async {
  final jpegToJxlIsolate = IsolateManager.create(
    convert,
    concurrent: 2,
  );
  var futures = jpegFiles.map((jpegFile) {
    return _updateJpegToJxlStat(jpegToJxlIsolate(jpegFile.path));
  });
  try {
    await futures.wait;
  } catch (e) {
    print("error while waiting all conversion to be done $e");
  }
  await jpegToJxlIsolate.stop();
}

Future<void> main() async {
  await processJpegFiles(
      [File("a.jpg"), File("b.jpg"), File("c.jpg"), File("d.jpg")]);
}

```
In the example above, the `print("fail $e");` statement is only executed 2 times when `concurrent: 2` is set, even though there are 4 tasks, and each should result in a failure. The `IsolateManager` does not properly handle cases where an isolate throws an exception.

Instead of considering the isolate as finished and moving on to process the next task in the queue, it halts further execution. This behavior causes some tasks to remain unprocessed, leading to incorrect overall results.

The expected behavior is that when an isolate throws an exception, it should be marked as completed, and the next task in the queue should be executed.

**Comment by lamnhan066** [comment]
I can reproduce this issue on both version `5.7.0+1` and `6.0.0-rc.8`.
