### ISSUE TITLE
Usage on the web

### ISSUE THREAD

**Issue by CrypticVader** [lamnhan066/isolate_manager#8]
This is how I created the controller:
```dart
final noteProcessorIsolateManager = IsolateManager.create(
    notesProcessor,
    workerName: 'worker',
    workerConverter: (p0) {
      // This message is not printed anywhere!
      log('worker message');
      return p0;
    },
  );
```
And here I compute using the function:
```dart
final adapted = await noteProcessorIsolateManager.compute((
          notes: data.$1,
          tags: data.$2,
          searchQuery: _searchParameter,
          groupProps: _groupProps,
          filterProps: _getFilterProps,
          sortProps: _sortProps,
        ));
```
This works fine on android, but nothing happens when I use it on the web.
I used the `worker.dart` file provided in the documentation, & didn't change anything in there.
I also tried logging within in `worker()` method in `worker.dart,` but that didn't print anything too.
The compiled `worker.js` file was placed in the same directory as `index.html`

**Comment by CrypticVader** [comment]
If I set `isDebug: true`, then this is printed in the IDE console:
![image](https://github.com/lamnhan066/isolate_manager/assets/61494838/b9710878-b6fc-4c4f-93d6-ede396d4c52d)

**Comment by lamnhan066** [comment]
> I used the worker.dart file provided in the documentation, & didn't change anything in there.
@CrypticVader Have you modified the method `worker` in the `worker.dart` as I mentioned in step 2 in the Doc?

**Comment by CrypticVader** [comment]
> > I used the worker.dart file provided in the documentation, & didn't change anything in there.
> 
> @CrypticVader Have you modified the method `worker` in the `worker.dart` as I mentioned in step 2 in the Doc?

No, how should I modify it though?
I didn't understand that step.

**Comment by lamnhan066** [comment]
@CrypticVader For instance, we have a function that we need to use for the Isolate:

``` dart
double add(double a, double b) => a + b;
```

Then the method `worker` in the `worker.dart` will be like:

``` dart
FutureOr<dynamic> worker(dynamic message) {
  return add(message[0], message[1]);
}
```

**Comment by CrypticVader** [comment]
Thank you for replying, I will try doing this

**Comment by lamnhan066** [comment]
@CrypticVader If you want to use `Worker` more effectively, convert all parameters and results to JSON (or String) before sending them.

**Comment by CrypticVader** [comment]
The compilation to worker.js fails with a lot of exceptions if I call my function inside worker.dart. My function has other dependencies like the DateTime library.

**Comment by lamnhan066** [comment]
@CrypticVader You need to move those functions to a separate file as I also mentioned in the doc to avoid depending on the Flutter library. When that file only depends on Dart native, the js compiler will work.

**Comment by lamnhan066** [comment]
Hi @CrypticVader , can you do it? I just added some [examples](https://github.com/lamnhan066/isolate_manager/tree/main/example/lib/web_workers) of using isolate for the Web platform.

**Comment by lamnhan066** [comment]
I'll close this issue because it's been a long time without a response. Feel free to re-open if you have any further issues.
